skin: "/assets/css/skins/dark.css"
locale: en
title: TON Development Blog
email: ruemura3.contact@gmail.com
description: A blog by a developer who believes in the future of TON and Telegram
baseurl: "/ton-dev-blog"
url: "https://ruemura3.github.io"
logo: "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
twitter:
  username: ruemura3

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed

paginate: 10
paginate_path: /page:num/

search_full_content: false

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"